### ISSUE TITLE
Please update to latest version of Komodo Edit/IDE!

### ISSUE THREAD

**Issue by DDynamic** [Defman21/atomik-komodo#1]
Hello,
I love the atomic skin. Please update it so it will work with the latest version of Komodo, **9.1**.

**Comment by Defman21** [comment]
It should works fine.

**Comment by DDynamic** [comment]
As you can see, some icons are messed up on the left-hand side.
![screen shot 2015-05-02 at 8 40 49 am](https://cloud.githubusercontent.com/assets/2935060/7441298/11309f3c-f0a7-11e4-8ca8-5c644d8862a6.png)

**Comment by Defman21** [comment]
This is not Atomik skin in the screenshot.

**Comment by DDynamic** [comment]
**Yes it is:**

![screen shot 2015-05-02 at 8 45 27 am](https://cloud.githubusercontent.com/assets/2935060/7441308/a439268c-f0a7-11e4-94f0-818365f2571c.png)

**Comment by Defman21** [comment]
Click "Apply".
The skin works for me
![screen](http://i.imgur.com/hWZT6N2.png)
Komodo IDE, version 9.0.1, build 87203, platform linux-x86_64.
Built on Wed Apr 15 01:51:06 2015.

**Comment by DDynamic** [comment]
That fixed it! Thank you ever so much.
