### ISSUE TITLE
invisible tabs

### ISSUE THREAD

**Issue by vnoel** [Defman21/atomik-komodo#2]
Thanks a lot for this great skin.

I have the following issue : the tabs are invisible in the tar bar, see screenshot.
This is on Komodo Edit, version 9.1.0, build 15786, platform macosx.
Built on Thu May 21 04:13:48 2015.

thanks
![screen shot 2015-05-27 at 15 57 39](https://cloud.githubusercontent.com/assets/731499/7837753/45b4735a-0489-11e5-9de8-b897832162ed.png)

**Comment by Defman21** [comment]
I cannot reproduce that. Maybe it's osx-only problem but I can't fix it (I have no mac computer)

**Comment by neurobashing** [comment]
it's a mac thing; I have it on my machines as well (latest OSX).

**Comment by Defman21** [comment]
Then as I said I'm not able to fix that because I'm not a OSX-user and don't have any Mac computer in my home. But I accept pull requests so if you want - you can try to fix that.

**Comment by neurobashing** [comment]
FWIW it also occurs on latest IDE, Windows 8. I'll take a look @ fixing on Mac, that might fix it on Windows as well.

**Comment by neurobashing** [comment]
adding z-index:1; to #editorviewbox>tabs>tab (retaining z-index:-1 on tab w/ hover, before, after) seems to fix it on my Mac (for the dark theme). Does this preserve your design on Linux?

**Comment by Defman21** [comment]
I'll try that and let you know.
